# Generated by Django 6.0.3 on 2026-03-16 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='market.entity'),
        ),
    ]
