# Generated by Django 6.0.3 on 2026-03-21 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_paper_trading'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('FOMC', 'FOMC'), ('CPI', 'CPI'), ('NFP', 'NFP'), ('GDP', 'GDP'), ('PMI', 'PMI'), ('OTHER', 'Other')], default='OTHER', max_length=12)),
                ('scheduled_at', models.DateTimeField()),
                ('country', models.CharField(default='US', max_length=64)),
                ('importance', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='EarningsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('scheduled_at', models.DateTimeField()),
                ('session', models.CharField(choices=[('PRE_MARKET', 'Pre-market'), ('POST_MARKET', 'Post-market'), ('DURING_MARKET', 'During market'), ('TBD', 'TBD')], default='TBD', max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scheduled_at', 'ticker'],
                'unique_together': {('ticker', 'scheduled_at')},
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset_minutes', models.PositiveIntegerField(default=60)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('earnings_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='market.earningsevent')),
                ('economic_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='market.economicevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('economic_event__isnull', False), ('earnings_event__isnull', True)), models.Q(('economic_event__isnull', True), ('earnings_event__isnull', False)), _connector='OR'), name='event_reminder_one_event_only')],
            },
        ),
    ]
