# Generated by Django 6.0.3 on 2026-03-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_economicevent_earningsevent_eventreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicevent',
            name='currency',
            field=models.CharField(default='USD', max_length=8),
        ),
    ]
