# Generated by Django 6.0.3 on 2026-03-21 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alertrule_alertevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('order_type', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit'), ('STOP', 'Stop')], default='MARKET', max_length=10)),
                ('shares', models.DecimalField(decimal_places=6, max_digits=15)),
                ('trigger_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('take_profit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('stop_loss_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('status_message', models.CharField(blank=True, max_length=255)),
                ('filled_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='market.paperportfolio')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='market.papertrade')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_equity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='market.paperportfolio')),
            ],
            options={
                'ordering': ['captured_at'],
            },
        ),
    ]
