# Generated by Django 6.0.3 on 2026-03-21 03:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_screenerpreset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlistitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='list_name',
            field=models.CharField(default='Default', max_length=80),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterUniqueTogether(
            name='watchlistitem',
            unique_together={('user', 'entity', 'list_name')},
        ),
    ]
